### ISSUE TITLE
Set "environment" to "preprod" for nightly tvOS application distributed on TestFlight

### ISSUE THREAD

**Issue by pyby** [SRGSSR/srganalytics-apple#37]
### Issue type

Incorrect behavior

Feature request

### Description of the problem

The SDK sets the `environment` property itself, regarding the build.

On iOS platform, developers use an in house code signing to distribute nightly and beta versions and a third party service, like Appcenter.

On tvOS platform, the easiest way to share a nighty and a beta version is the Apple TestFlight service. Application are built with an AppStore code signing, which set `environment` to `prod`.

Here is a playback start report for Letterbox nighty on tvOS:
[letterbox_tvos_nighlty_playback_start_report.json.zip](https://github.com/SRGSSR/srganalytics-apple/files/4174244/letterbox_tvos_nighlty_playback_start_report.json.zip)
### Excepted behaviour

It would be better for analyse tools to set `preprod` on non production build, like on iOS platform.

### Environment information

* Library version: 2.0.0
* iOS version: Any
* Device: Any

### Reproducibility

Always reproducible

### Steps to reproduce

1. Deploy a new Letterbox nighty or beta version for tvOS on Apple TestFlight (or download an existing one)
2. Open the application and play a media.
3. Check analytics report, and `environment` value.

**Comment by defagos** [comment]
Not sure how we could make a difference between betas and nightlies distributed through Testflight, since currently prod is basically equal to Testflight in our test.

... except with an additional configuration flag or some naming convention we could document, but is it a good idea?

**Comment by pyby** [comment]
I propose an optional configuration option, like `centralized` and `unitTesting`.
By default, nothing change.
If a TestFlight build wants to be flagged at a pre production build, or an In House build as a production build, this option can override the default automatic choice.

Proposition is on `feature/environment-option`.
