### ISSUE TITLE
Ghost page view

### ISSUE THREAD

**Issue by pyby** [SRGSSR/srganalytics-apple#55]
### Issue type

Incorrect behavior

### Description of the problem

When investigating #54, we discovered that some page view events are sent when the application is in background.

### Environment information

* Library version: 7.0+
* iOS / tvOS version: Any
* Device: Any

### Reproducibility

Always reproducible

### Steps to reproduce

1. Launch and kill the application.
2. User AirShip to sent a push notification.
3. If the application is launched in background, a page view is sent.

**Comment by defagos** [comment]
Fixed in 7.0.4 by inhibiting all page view events when the application state is background.
