### ISSUE TITLE
Prevent ComScore AdSupport usage

### ISSUE THREAD

**Issue by pyby** [SRGSSR/srganalytics-apple#56]
### Issue type

Improvement

### Description of the problem

When starting the application in debug, a log is displayed:
`The comScore library detected AdSupport.framework is not present. This prevents the application usage data from being correctly included in comScore's syndicated reporting products. Please refer to the comScore library implementation document for instructions on including AdSupport.framework for correct syndicated reporting inclusion of the application usage data.`

It's the correct behaviour, as the SDK does not use `AdSupport.framework`: #51.

### Environment information

* Library version: 7.1.0
* iOS / tvOS version: Any
* Device: Any

### Reproducibility

Always reproducible

**Comment by pyby** [comment]
Declaring `preventAdSupportUsage` in configuration removes the message in logs.

See `feature/prevent-ad-support-usage` branch.

**Comment by defagos** [comment]
Nice find, thanks!
