### ISSUE TITLE
Test selected segment at stream end regression with iOS/tvOS SDK 15.3

### ISSUE THREAD

**Issue by pyby** [SRGSSR/srganalytics-apple#58]
### Issue type

Incorrect behavior

### Description of the problem

The `testSelectedSegmentAtStreamEnd` test failed since we the project switch to Xcode 13.3.0.

### Environment information

See https://github.com/SRGSSR/srgmediaplayer-apple/issues/115 issue.

* Library version: Any
* iOS / tvOS version: Any
* Device: Any

### Reproducibility

Always reproducible

### Steps to reproduce

1. Run `testSelectedSegmentAtStreamEnd` test in `ComScoreMediaPlayerTestCase` and `MediaPlayerTestCase` cases.

**Comment by defagos** [comment]
Work fine with Xcode 14. I uncommented these tests again as we will now be running tests with Xcode 14.
